"""New show_no in Users

Revision ID: f65b0da9e377
Revises: 899cb5cc0614
Create Date: 2024-09-24 17:09:10.622385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65b0da9e377'
down_revision: Union[str, None] = '899cb5cc0614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_no', sa.Integer(), nullable=True))
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'show_no')
    # ### end Alembic commands ###
